project_id = "lucidblocks"

[functions.submit-issue]
verify_jwt = false

[functions.create-upload-url]
verify_jwt = false

[functions.download]
verify_jwt = false

[functions.purge-attachments]
verify_jwt = false

[functions.submit-comment]
verify_jwt = false

[functions.notify]
verify_jwt = false
